"""empty message

Revision ID: 0833813e200e
Revises: 8ded0bb6dd7c
Create Date: 2020-07-29 06:45:21.308592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0833813e200e'
down_revision = '8ded0bb6dd7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('score_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components', 'score_type')
    # ### end Alembic commands ###
