"""empty message

Revision ID: b86547139df8
Revises: 8ded0bb6dd7c
Create Date: 2020-08-26 08:43:31.343139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86547139df8'
down_revision = '8ded0bb6dd7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('score_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components', 'score_type')
    # ### end Alembic commands ###
